import {
  CalendarOutlined,
  DeliveredProcedureOutlined,
  DesktopOutlined,
  FileAddOutlined,
  GiftOutlined,
  HomeOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  PhoneOutlined,
  PlaySquareOutlined,
  QuestionCircleOutlined,
  RocketOutlined,
  SettingOutlined,
  ShopOutlined,
  TeamOutlined,
  UnorderedListOutlined,
  UserAddOutlined,
  MobileOutlined,
  EyeOutlined,
  PayCircleOutlined,
  TagOutlined,
  FormOutlined,
  LikeOutlined,
  InboxOutlined,
  CreditCardOutlined,
  FundProjectionScreenOutlined,
  UserOutlined,
  InfoCircleOutlined,
} from '@ant-design/icons';

// 바슈롬 어드민
export const ADMIN_LIST = [
  {
    key: '1',
    icon: <HomeOutlined />,
    label: 'HOME',
    path: '/admin',
  },
  {
    key: 'sub1',
    icon: <InboxOutlined />,
    label: '주문',
    path: '/admin/order/weborder',
    children: [
      {
        label: '제품 오더 관리',
        icon: <UnorderedListOutlined />,
        key: 'product order',
        path: '/admin/order/weborder',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
      {
        label: '쿠폰 거래 내역',
        icon: <UnorderedListOutlined />,
        key: 'sales list',
        path: '/admin/order/coupon-sales',
        sub: '판매 등록',
        detail: '판매 상세',
        set: 'defaultTitle',
      },
      {
        label: '적립금 제품 주문 내역',
        icon: <UnorderedListOutlined />,
        key: 'point list',
        path: '/admin/order/point-sales',
        sub: '주문 등록',
        detail: '주문 상세',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub2',
    icon: <EyeOutlined />,
    label: '제품',
    path: '/admin/product/manage',
    children: [
      {
        label: '제품 관리',
        icon: <UnorderedListOutlined />,
        key: 'product manage',
        path: '/admin/product/manage',
        sub: '제품 등록',
        detail: '제품 상세',
        set: '증정 제품 관리',
      },
      {
        label: '제품 그룹 설정',
        icon: <UnorderedListOutlined />,
        key: 'product group',
        path: '/admin/product/group-manage',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
      {
        label: '상품 정보 관리',
        icon: <UnorderedListOutlined />,
        key: 'product info manage',
        path: '/admin/product/page-manage',
        sub: '상품 등록',
        detail: '상품 상세',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub3',
    icon: <ShopOutlined />,
    label: '스토어',
    path: '/admin/store/manage',
    children: [
      {
        label: '스토어 관리',
        icon: <UnorderedListOutlined />,
        key: 'store list',
        path: '/admin/store/manage',
        sub: 'defaultTitle',
        detail: '스토어 상세',
        set: 'defaultTitle',
      },
      {
        label: '스토어 그룹 관리',
        icon: <UnorderedListOutlined />,
        key: 'store group',
        path: '/admin/store/group',
        sub: 'defaultTitle',
        detail: '스토어 그룹 관리 상세',
        set: 'defaultTitle',
      },
      // {
      //   label: '안경사 관리',
      //   icon: <UnorderedListOutlined />,
      //   key: 'optician manage',
      //   path: '/admin/store/optician',
      //   sub: '안경사 등록',
      //   detail: '안경사 상세',
      //   set: 'defaultTitle',
      // },
    ],
  },
  {
    key: 'sub4',
    icon: <CreditCardOutlined />,
    label: '적립금',
    path: '/admin/point/manage',
    children: [
      {
        label: '적립금 관리',
        icon: <UnorderedListOutlined />,
        key: 'point manage',
        path: '/admin/point/manage',
        sub: '적립금 등록',
        detail: '적립금 상세',
        set: 'defaultTitle',
      },
      {
        label: '적립금 내역 관리',
        icon: <UnorderedListOutlined />,
        key: 'point history',
        path: '/admin/point/list',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub5',
    icon: <FundProjectionScreenOutlined />,
    label: '캠페인',
    path: '/admin/campaign/promotion',
    children: [
      // {
      //   label: '프로모션 관리',
      //   icon: <UnorderedListOutlined />,
      //   key: 'promotion manage',
      //   path: '/admin/campaign/promotion',
      //   sub: '프로모션 등록',
      //   detail: '프로모션 상세',
      //   set: 'defaultTitle',
      // },
      {
        label: '쿠폰 관리',
        icon: <UnorderedListOutlined />,
        key: 'coupon manage',
        path: '/admin/campaign/coupon',
        sub: '쿠폰 등록',
        detail: '쿠폰 상세',
        set: '회원 쿠폰 재발급',
      },
    ],
  },
  {
    key: 'sub6',
    icon: <UserOutlined />,
    label: '회원',
    path: '/admin/member',
    children: [
      {
        label: '회원 관리',
        icon: <UnorderedListOutlined />,
        key: 'user manage',
        path: '/admin/member',
        sub: 'defaultTitle',
        detail: '회원 상세',
        set: '탈퇴 회원 관리',
      },
    ],
  },
  // {
  //   key: 'sub7',
  //   icon: <InfoCircleOutlined />,
  //   label: '고객지원',
  //   path: '/admin/support/news',
  //   children: [
  //     {
  //       label: '뉴스 관리',
  //       icon: <UnorderedListOutlined />,
  //       key: 'news manage',
  //       path: '/admin/support/news',
  //       sub: '뉴스 등록',
  //       detail: '뉴스 상세',
  //       set: 'defaultTitle',
  //     },
  //     {
  //       label: 'FAQ 관리',
  //       icon: <UnorderedListOutlined />,
  //       key: 'faq manage',
  //       path: '/admin/support/faq',
  //       sub: 'FAQ 등록',
  //       detail: 'FAQ 상세',
  //       set: '카테고리 관리',
  //     },
  //     {
  //       label: '1:1문의(APP)',
  //       icon: <UnorderedListOutlined />,
  //       key: 'inquiry manage',
  //       path: '/admin/support/inquiry-one',
  //       sub: 'defaultTitle',
  //       detail: '1:1 문의 상세',
  //       set: '카테고리 관리',
  //     },
  //     {
  //       label: '배너 관리',
  //       icon: <UnorderedListOutlined />,
  //       key: 'banner manage',
  //       path: '/admin/support/banner',
  //       sub: '배너 등록',
  //       detail: '배너 상세',
  //       set: 'defaultTitle',
  //     },
  //     {
  //       label: '약관 관리',
  //       icon: <UnorderedListOutlined />,
  //       key: 'terms manage',
  //       path: '/admin/support/terms',
  //       sub: '약관 등록',
  //       detail: '약관 상세',
  //       set: 'defaultTitle',
  //     },
  //   ],
  // },
  {
    key: 'sub8',
    icon: <SettingOutlined />,
    label: '설정',
    path: '/admin/setting/account-manage',
    children: [
      {
        label: '어드민 계정관리',
        icon: <UnorderedListOutlined />,
        key: 'admin manage',
        path: '/admin/setting/account-manage',
        sub: 'defaultTitle',
        detail: '어드민 계정 상세',
        set: '권한 설정',
      },
      // {
      //   label: '어드민 로그 조회',
      //   icon: <UnorderedListOutlined />,
      //   key: 'log list',
      //   path: '/admin/setting/log-manage',
      //   sub: 'defaultTitle',
      //   detail: 'defaultTitle',
      //   set: 'defaultTitle',
      // },
      // {
      //   label: '어드민 IP 관리',
      //   icon: <UnorderedListOutlined />,
      //   key: 'ip manage',
      //   path: '/admin/setting/ip-manage',
      //   sub: 'defaultTitle',
      //   detail: 'defaultTitle',
      //   set: 'defaultTitle',
      // },
      {
        label: '비밀번호 변경',
        icon: <UnorderedListOutlined />,
        key: 'pw reset',
        path: '/admin/setting/pw-manage',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
    ],
  },
];
// 바슈롬 앱
export const APP_LIST = [
  {
    key: '1',
    icon: <ShopOutlined />,
    label: 'HOME',
    path: '/app/main',
  },
  {
    key: 'sub1',
    icon: <TeamOutlined />,
    label: '공지',
    path: '/app/notice/pop-up',
    children: [
      {
        label: '팝업 관리',
        icon: <UnorderedListOutlined />,
        key: 'user list',
        path: '/app/notice/pop-up',
        sub: '팝업 등록',
        detail: '팝업 상세',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub2',
    icon: <HomeOutlined />,
    label: '홍보',
    path: '/app/advertise/video',
    children: [
      {
        label: '광고영상 관리',
        icon: <UnorderedListOutlined />,
        key: 'advertise list',
        path: '/app/advertise/video',
        sub: '광고영상 등록',
        detail: '광고영상 상세',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub3',
    icon: <HomeOutlined />,
    label: '버전',
    path: '/app/version/manage',
    children: [
      {
        label: '앱 버전 관리',
        icon: <UnorderedListOutlined />,
        key: 'version list',
        path: '/app/version/manage',
        sub: '앱 버전 등록',
        detail: '앱 버전 상세',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub4',
    icon: <HomeOutlined />,
    label: '약관 (App)',
    path: '/app/terms-app/manage',
    children: [
      {
        label: '안경원 리스트',
        icon: <UnorderedListOutlined />,
        key: 'terms-app list',
        path: '/app/terms-app/manage',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
    ],
  },
];
// 렌즐리
export const LENSLY_LIST = [
  {
    key: '1',
    icon: <ShopOutlined />,
    label: 'HOME',
    path: '/lensly/main',
  },
  {
    key: 'sub2',
    icon: <HomeOutlined />,
    label: '예약',
    path: '/lensly/reservation/weborder',
    children: [
      {
        label: '예약 관리',
        icon: <UnorderedListOutlined />,
        key: 'weborder list',
        path: '/lensly/reservation/weborder',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub3',
    icon: <NotificationOutlined />,
    label: '상품문의',
    path: '/lensly/inquiry-product/manage',
    children: [
      {
        label: '상품문의 관리',
        icon: <DeliveredProcedureOutlined />,
        key: 'terms list',
        path: '/lensly/inquiry-product/manage',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub4',
    icon: <PlaySquareOutlined />,
    label: '배너 관리',
    path: '/lensly/banner/manage',
    children: [
      {
        label: '배너 등록/수정',
        icon: <FileAddOutlined />,
        key: 'banner upsert',
        path: '/lensly/banner/manage',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub5',
    icon: <SettingOutlined />,
    label: '가이드',
    path: '/lensly/guide/manage',
    children: [
      {
        label: '가이드 관리',
        icon: <UnorderedListOutlined />,
        key: 'account list',
        path: '/lensly/guide/manage',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
    ],
  },
  {
    key: 'sub6',
    icon: <SettingOutlined />,
    label: '약관',
    path: '/lensly/terms/manage',
    children: [
      {
        label: '약관 관리',
        icon: <UnorderedListOutlined />,
        key: 'account list',
        path: '/lensly/terms/manage',
        sub: 'defaultTitle',
        detail: 'defaultTitle',
        set: 'defaultTitle',
      },
    ],
  },
];

export const ADMIN_DETAIL = [
  {
    label: 'HOME',
    path: '/lensly/main',
  },
];

export const rightAdminMenuSummary = [
  {
    text: `렌즐리 웹사이트\n바로가기`,
    link: 'https://lensly.co.kr',
    icon: <DesktopOutlined className={'menuIcon'} />,
    children: [],
  },
  {
    text: `렌즐리 어드민\n바로가기`,
    link: 'https://admin.lensly.co.kr/login',
    icon: <EyeOutlined className={'menuIcon'} />,
    children: [],
  },
  // {
  //   text: `바슈롬 앱 어드민\n바로가기`,
  //   link: 'https://admin.lensly.co.kr/app',
  //   icon: <MobileOutlined className={'menuIcon'} />,
  //   children: [],
  // },
];
